package com.alexlis.tests;

import com.alexlis.domain.MenuItem;
import com.alexlis.helpers.TestBase;
import com.alexlis.pages.PageObjects;
import com.alexlis.pages.SearchValue;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

public class SimpleTests extends TestBase {

    PageObjects pageObjects = new PageObjects();
    SearchValue searchValue = new SearchValue();

    @Tag("Simple")
    @EnumSource(MenuItem.class)
    @ParameterizedTest(name = "Проверка результатов поиска значения: {0}")
    void searchQueryTest(MenuItem menuItem) {
        pageObjects.openPage();
        pageObjects.confirmAge();
        pageObjects.regionConfirm();
        searchValue.searchQuery(menuItem);

        pageObjects.checkResultIncorrectSearchPage();
    }

    @Tag("Simple")
    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        pageObjects.openPage();

        pageObjects.simpleCheckTitle();
    }
}